services:
  - type: web
    name: shzorik-telegram-webhook
    runtime: python  # Change from 'env: python' to this
    pythonVersion: "3.12"  # Add this line
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      # Важные переменные окружения
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_SECRET_TOKEN
        sync: false